#! /bin/sh
#
# chkconfig: 35 99 01
# description: Collects finished CE job event records

. /etc/init.d/functions

PIDFILE=/var/run/batchacct/batchacct-cecold.pid
LOGFILE=/var/log/batchacct/batchacct-cecold.log
USER=root

start () {
    echo -n "Starting CE accounting daemon: "
    daemon --pidfile $PIDFILE --user $USER \
        python /usr/lib/python2.4/site-packages/batchacct/whisk.py \
        -c /etc/batchacct/connection \
        -a /opt/glite/var/log/accounting \
        -l $LOGFILE \
        -p $PIDFILE
    echo
}

stop () {
    echo -n "Stopping CE accounting daemon: "
    killproc -p $PIDFILE
    echo
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    *)

    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
